baseURL = 'https://miphphuong-eng.github.io/NguyenMinhPhuong_Workshop/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = "Internship Report"
theme = "hugo-theme-learn"

# Quan trọng: Đảm bảo đường dẫn file CSS/JS luôn đúng
relativeURLs = false
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    title = "Worklog & Workshop"
    weight = 1
    languageName = "English"
  [languages.vi]
    title = "Nhật ký thực tập"
    weight = 2
    languageName = "Tiếng Việt"

[params]
  themeVariant = "blue"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
