baseURL = 'https://miphphuong-eng.github.io/NguyenMinhPhuong_Workshop/'
relativeURLs = true
canonifyURLs = false
languageCode = 'en-us'
title = "Internship Report"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "miphphuong"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
